### ISSUE TITLE
최종 발표 준비

### ISSUE THREAD

**Issue by baldwinIV** [boostcampwm-2022/Web35-CryptoGraph#119]
### 요약

12월 14일까지 해당 영상을 작성해 제출해야한다.
시연 영상: 주요 기능 시연 녹화본 (1분 내외)
발표 영상: “프로젝트에서 어떤 기술적인 경험을 했는가?”에 대한 발표 녹화본 (10분 내외)

 영상은 유튜브 업로드한 후 링크를 “프로젝트 소개 페이지” 속성에 추가한다.

### 예상 작업 내용 (커밋단위)

- [x] 시연 영상 녹화하기
- [x] 발표 영상 녹화하기
- [x] 발표 영상 유튜브에 업로드하기
- [x] 링크를 프로젝트 소개 페이지에 달기

### 이슈가 완료된 후 (TOBE)
해방된 감자가 될 수 있다.

### 기타
 유종의 미를 거둡시다. 힘들지만 화이팅~

**Comment by rkdwoals159** [comment]
해방된 potato가 되었습니다.
