### ISSUE TITLE
반응형 메인/디테일 레이아웃 모바일 지원

### ISSUE THREAD

**Issue by sronger** [boostcampwm-2022/Web35-CryptoGraph#23]
### 요약

* 메인/디테일 페이지의 반응형으로 모바일, 데스크탑을 자연스럽게 지원한다. 메인페이지 반응형은 #22 에서 작성하여 남은 부분에 대해 코드를 마무리한다.

### 예상 작업 내용 (커밋단위)

- [ ] 메인페이지 모바일 대응
- [ ] 디테일 페이지 반응형 대응
- [ ] 디테일 페이지 모바일 대응

### 이슈가 완료된 후 (TOBE)
메인/모바일 페이지의 반응형 레이아웃이 완료되어, 이제 각 레이아웃에 들어갈 컴포넌트를 분업하여 개발할 수 있게 된다. 

### 기타
 - #22 가 merge된 이후 개발에 들어가야 한다.
 - 이미 개발이 진행되고 있는 `candleChart`또한 고정 width가 아니라 변수를 통해 가변 크기를 지원해야한다.

**Comment by baldwinIV** [comment]
build 라벨이 붙은 이유가 있을까용?
 npm으로 여러 모듈이 설치되거나 해서 플젝이 변경될때 붙이는 라벨이라고 생각하고 있었습니다.
