### ISSUE TITLE
recoil 세팅

### ISSUE THREAD

**Issue by rkdwoals159** [boostcampwm-2022/Web35-CryptoGraph#26]
### 요약

다크모드 작업 및 전역변수 관리를 위해 recoil 세팅을 하겠습니다.

### 예상 작업 내용 

- [ ] recoil 설치
- [ ] recoil이 css / ssr 환경에서 모두 정상적으로 작동하게 세팅

### 이슈가 완료된 후 (TOBE)
기존에는 깊게 drilling된 컴포넌트들이 있어서 전역변수의 필요성이 대두되지않았지만 추후 다크모드 지원 및 유지보수의 측면 에서 전역변수 상태관리가 필요하다고 판단, recoil로 관리가능합니다.

**Comment by baldwinIV** [comment]
일단 안할거 같아서 close
