### ISSUE TITLE
코인 정보 표시 컴포넌트 개발

### ISSUE THREAD

**Issue by baldwinIV** [boostcampwm-2022/Web35-CryptoGraph#35]
### 요약

<img width="646" alt="image" src="https://user-images.githubusercontent.com/60903175/203702377-3abbca79-1e82-4d49-b786-d2363e2bacef.png">
- `coinmarketcap`에서 받아온 코인에 대한 metadata를 뿌려주는 리액트 컴포넌트를 작성한다.

### 예상 작업 내용 (커밋단위)

- [ ] 코인마켓캡에서 받아오는 API 데이터를 사용하는 커스텀 훅 생성
- [ ] 반응형에 맞게 컴포넌트 레이아웃 작성

### 이슈가 완료된 후 (TOBE)
사이드바 및 메인 페이지에 활용될 코인 정보 컴포넌트가 작성된다. 

### 기타
- #43 이슈가 선행되어야함

**Comment by kongyb** [comment]
#60 #43 에서 각각의 task 처리하였으므로 close합니다.
