### ISSUE TITLE
트리맵 차트 스타일링

### ISSUE THREAD

**Issue by sronger** [boostcampwm-2022/Web35-CryptoGraph#38]
### 요약

트리맵 차트 스타일링

### 예상 작업 내용 (커밋단위)

- [ ] 트리맵 border 추가
- [ ] 트리맵 radius 추가
- [ ] 트리맵 color 수정
- [ ] transision 추가
- [x] ticker sort 기능 추가
- [x] 데이터 바인딩 전 초기 화면 렌더 방지

### 생각해볼 점
- 데이터 바인딩 되기 전 잠깐의 대기시간 발생 (1초 + a)

### 이슈가 완료된 후 (TOBE)
이슈가 완료된 이후 변화한 점/기대할 수 있는 점 등을 간단히 요약

### 기타
 해당 이슈에서 예상되는 trouble? 혹은 리팩터링 포인트, 아니면 공유하고 싶은 기타 등등

**Comment by baldwinIV** [comment]
아 그리고 데이터 sort도 추가해야할 것 같습니다.
