### ISSUE TITLE
[러닝차트] 일정확률로 모두 1%로 고정되는 issue

### ISSUE THREAD

**Issue by rkdwoals159** [boostcampwm-2022/Web35-CryptoGraph#77]
### 요약

일정확률로 모두 1%에서 더이상 바뀌지않는 버그를 수정합니다.
아마도 init data의 value가 1로 되어있는데 그 이후 data update가 되지않을때의 오류인것 같습니다.

### 예상 작업 내용 (커밋단위)

- [ ] 실시간 등락률 데이터 fetch 함수 체크
- [ ] 잘 작동되도록 수정

### 이슈가 완료된 후 (TOBE)
차트가 일정확률로 오류나는 에러를 더이상 나타나지 않게 합니다.

**Comment by baldwinIV** [comment]
react useEffect 훅에서 dependency를 모두 설정해줬는지 체크해보고, 흠.. 라이프사이클 추적해가면서 로직 이상한 부분을 찾아봐야곘군요

**Comment by baldwinIV** [comment]
이거 close왜 안되죠 (PR이랑 연결 안된듯) 제가 close 시키겠습니다.
