### ISSUE TITLE
[러닝차트/트리차트] 차트색상 빨강/파랑으로 변경 + 기존 opacity에서 d3 color scale로 변경

### ISSUE THREAD

**Issue by rkdwoals159** [boostcampwm-2022/Web35-CryptoGraph#78]
### 요약

아래 사진처럼 어두운 색상이 랜덤으로 걸릴경우 글자색이 보이지않습니다.

![image](https://user-images.githubusercontent.com/61281128/205251288-058e9a6e-061f-4e7d-990e-ea9b6514ef37.png)

### 예상 작업 내용 (커밋단위)

- [ ] 러닝차트 기존 랜덤색상에서 빨강/파랑으로 변경
- [ ] 러닝/트리차트 명도를 결정하는 수단으로 기존 css opacity에서 d3 color scale로 변경

### 이슈가 완료된 후 (TOBE)
더이상 글자색이 어두워서 차트안에 이름이 가려지는 상황이 일어나지 않습니다.

**Comment by baldwinIV** [comment]
랜덤 색보다, 상승한 코인의 경우엔 진한 빨강, 하락하고 있는 녀석에 대해서는 진한 파랑이 낫지 않을까요?

**Comment by rkdwoals159** [comment]
넵 그렇게 진행해볼게요
